# Generated by Django 5.0.6 on 2024-08-03 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("book", "0002_review"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="date",
            field=models.DateField(auto_now_add=True, default="2024-08-02"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="review",
            name="rating",
            field=models.DecimalField(decimal_places=1, default=5, max_digits=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="review",
            name="review",
            field=models.TextField(default="First Review"),
            preserve_default=False,
        ),
    ]
