# Generated by Django 5.0.6 on 2024-08-05 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("book", "0003_review_date_review_rating_review_review"),
    ]

    operations = [
        migrations.AlterField(
            model_name="author",
            name="photo",
            field=models.ImageField(null=True, upload_to="uploads/"),
        ),
        migrations.AlterField(
            model_name="review",
            name="rating",
            field=models.DecimalField(decimal_places=1, default=5.0, max_digits=3),
        ),
        migrations.AlterField(
            model_name="review",
            name="review",
            field=models.TextField(null=True),
        ),
    ]
